#!/bin/sh
# Writes load-tests/.env.loadtest (git-ignored by the root `.env.*` rule) from
# .env.example with fresh throwaway secrets and non-default host ports, so the
# load-test stack never reads, needs or touches a developer's own `.env`.
#
#   sh load-tests/make-env.sh          # refuses to overwrite an existing file
#   sh load-tests/make-env.sh --force  # regenerate
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(dirname -- "$here")
out="$here/.env.loadtest"

if [ -e "$out" ] && [ "${1:-}" != "--force" ]; then
  echo "$out exists; pass --force to regenerate" >&2
  exit 1
fi

rand() { od -An -tx1 -N"${1:-16}" /dev/urandom | tr -d ' \n'; }

# key=value lines appended after the template win (Compose takes the last
# definition of a key in an env file).
{
  cat "$root/.env.example"
  cat <<EOF

# ---- load-test overrides (generated by load-tests/make-env.sh) ----
COMPOSE_PROJECT_NAME=loadtest
PORT=3261
GRAFANA_PORT=3262
PROMETHEUS_PORT=3263
MINIO_CONSOLE_PORT=3264
KAFKA_UI_PORT=3265
JAEGER_UI_PORT=3266
PRIVATE_NETWORK_SUBNET=172.28.50.0/24
DB_PASSWORD=lt_db_$(rand 12)
REPLICATION_PASSWORD=lt_repl_$(rand 12)
ANALYTICS_DB_PASSWORD=lt_an_$(rand 12)
METRICS_TOKEN=lt_metrics_$(rand 16)
METRICS_DB_PASSWORD=lt_mdb_$(rand 12)
GRAFANA_ADMIN_PASSWORD=lt_graf_$(rand 8)
JWT_SECRET=lt_jwt_$(rand 24)
OAUTH_SESSION_SECRET=lt_oauth_$(rand 24)
MINIO_ROOT_PASSWORD=lt_minio_$(rand 12)
S3_SECRET_ACCESS_KEY=lt_s3_$(rand 16)
BACKUP_S3_SECRET_ACCESS_KEY=lt_bk_$(rand 12)
RESTORE_S3_SECRET_ACCESS_KEY=lt_rs_$(rand 12)
CORS_ORIGINS=http://localhost:5173
# Tracing stays OFF during measurements: exporting every span would add
# CPU/network work that is not part of what is measured.
OTEL_EXPORTER_OTLP_ENDPOINT=
EOF
} > "$out"
echo "wrote $out"
